### ISSUE TITLE
Condition on batch delete message

### ISSUE THREAD

**Issue by sidashah** [bawejakunal/Frame-Seller#28]
Check the length of processed messages when sending batch message delete in the queue.

According to this:
EmptyBatchRequest: An error occurred (AWS.SimpleQueueService.EmptyBatchRequest) when calling the DeleteMessageBatch operation: There should be at least one DeleteMessageBatchRequestEntry in the request.

**Comment by bawejakunal** [comment]
Fixed in 4f2bbbbec326fe9d5b0ac95e1257f06cfdf6b8bd
